language: python
python:
    - "3.5"
addons:
    chrome: stable
env:
    - PATH=$PATH:/usr/lib/chromium-browser/ DISPLAY=:99.0 CHROME_BIN=/usr/bin/google-chrome
install:
    - sudo apt-get update
    - sudo apt-get install chromium-chromedriver
    - sh -e /etc/init.d/xvfb start
    - pip install -r requirements.txt
script:
    - pytest



